name: openblas-src

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  windows-msvc:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        triple:
          - x64-windows
          - x64-windows-static
          - x64-windows-static-md
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: ./vcpkg
        key: vcpkg-openblas
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git --depth 1
        cd vcpkg
        ./bootstrap-vcpkg.bat
    - name: Install OpenBLAS by vcpkg
      run: |
        ./vcpkg/vcpkg.exe install openblas:${{ matrix.triple }}

    - uses: actions-rs/cargo@v1
      name: Test features=system
      with:
        command: test
        args: --features=system --manifest-path=openblas-src/Cargo.toml
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      if: ${{ matrix.triple == 'x64-windows' }}

    - uses: actions-rs/cargo@v1
      name: Test features=system,static
      with:
        command: test
        args: --features=system,static --manifest-path=openblas-src/Cargo.toml
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      if: ${{ matrix.triple == 'x64-windows-static-md' }}

    - uses: actions-rs/cargo@v1
      name: Test features=system,static with crt-static
      with:
        command: test
        args: --features=system,static --manifest-path=openblas-src/Cargo.toml
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        RUSTFLAGS: "-C target-feature=+crt-static"
      if: ${{ matrix.triple == 'x64-windows-static' }}

  macos:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        feature:
          - ""
          - static
          - system
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: Install OpenBLAS by homebrew
      run: |
        brew install openblas
      if: ${{ contains(matrix.feature, 'system') }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --features=${{ matrix.feature }}
          --manifest-path=openblas-src/Cargo.toml

  linux:
    runs-on: ubuntu-18.04
    container:
      image: rust
    strategy:
      fail-fast: false
      matrix:
        feature:
          - ""
          - static
          - system
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: Install gfortran by apt
      run: |
        apt update
        apt install -y gfortran
    - name: Install OpenBLAS by apt
      run: |
        apt update
        apt install -y libopenblas-dev
      if: ${{ contains(matrix.feature, 'system') }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --features=${{ matrix.feature }}
          --manifest-path=openblas-src/Cargo.toml
