name: test

on: [push]

jobs:
  test:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target          
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features

# name: Rust
#
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
#
# env:
#   CARGO_TERM_COLOR: always
#
# jobs:
#   build:
#
#     runs-on: ubuntu-latest
#
#     steps:
#     - uses: actions/checkout@v3
#     - name: Build
#       run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose && cargo clippy && cargo fmt
